# Generated by Django 4.1.3 on 2022-11-09 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_coustomer_registerdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coustomer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coustomer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coustomer',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coustomer',
            name='registerdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 16, 9, 33, 27272), null=True),
        ),
        migrations.RemoveField(
            model_name='coustomer',
            name='services',
        ),
        migrations.AddField(
            model_name='coustomer',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.service'),
        ),
    ]
