# Generated by Django 4.1.3 on 2022-11-09 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_coustomer_age_alter_coustomer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer',
            name='registerdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 16, 10, 21, 393747), null=True),
        ),
        migrations.RemoveField(
            model_name='coustomer',
            name='services',
        ),
        migrations.AddField(
            model_name='coustomer',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='employee.service'),
        ),
    ]
